# Generated by Django 5.1.6 on 2025-03-16 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registeraddress',
            options={'verbose_name': 'RegisterAddress', 'verbose_name_plural': 'RegisterAddress'},
        ),
    ]
