# Generated by Django 5.1.6 on 2026-07-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0008_order_idempotency_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="confirmation_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="confirmation_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("sending", "Sending"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="currency",
            field=models.CharField(default="NGN", max_length=3),
        ),
        migrations.AddField(
            model_name="payment",
            name="failure_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="payment",
            name="provider",
            field=models.CharField(default="paystack", max_length=20),
        ),
        migrations.AddField(
            model_name="payment",
            name="provider_channel",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="payment",
            name="provider_paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="provider_transaction_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
